from nltk import ngrams
from nltk.util import ngrams

#unigram model
n = 1
sentence = 'Mars is the fourth planet from the Sun in our solar system, often referred to as the “Red Planet” due to its reddish appearance caused by iron oxide on its surface. Known for its towering volcanoes, vast deserts, and polar ice caps, Mars has long fascinated scientists as a potential candidate for future human exploration.'

unigrams = ngrams(sentence.split(), n)
print(f"\n***********   UNIGRAM    ************************")
for item in unigrams:
    print(item)
    
#bigram model
n = 2
sentence = 'Mars is the fourth planet from the Sun in our solar system, often referred to as the “Red Planet” due to its reddish appearance caused by iron oxide on its surface. Known for its towering volcanoes, vast deserts, and polar ice caps, Mars has long fascinated scientists as a potential candidate for future human exploration.'

unigrams = ngrams(sentence.split(), n)
print(f"\n***********   BIGRAM    ************************")
for item in unigrams:
    print(item)

#trigram model
n = 3
sentence = 'Mars is the fourth planet from the Sun in our solar system, often referred to as the “Red Planet” due to its reddish appearance caused by iron oxide on its surface. Known for its towering volcanoes, vast deserts, and polar ice caps, Mars has long fascinated scientists as a potential candidate for future human exploration.'
unigrams = ngrams(sentence.split(), n)
print(f"\n***********   TRIGRAM    ************************")
for item in unigrams:
    print(item)

# ***********   UNIGRAM    ************************
# ('Mars',)
# ('is',)
# ('the',)
# ('fourth',)
# ('planet',)
# ('from',)
# ('the',)
# ('Sun',)
# ('in',)
# ('our',)
# ('solar',)
# ('system,',)
# ('often',)
# ('referred',)
# ('to',)
# ('as',)
# ('the',)
# ('“Red',)
# ('Planet”',)
# ('due',)
# ('to',)
# ('its',)
# ('reddish',)
# ('appearance',)
# ('caused',)
# ('by',)
# ('iron',)
# ('oxide',)
# ('on',)
# ('its',)
# ('surface.',)
# ('Known',)
# ('for',)
# ('its',)
# ('towering',)
# ('volcanoes,',)
# ('vast',)
# ('deserts,',)
# ('and',)
# ('polar',)
# ('ice',)
# ('caps,',)
# ('Mars',)
# ('has',)
# ('long',)
# ('fascinated',)
# ('scientists',)
# ('as',)
# ('a',)
# ('potential',)
# ('candidate',)
# ('for',)
# ('future',)
# ('human',)
# ('exploration.',)

# ***********   BIGRAM    ************************
# ('Mars', 'is')
# ('is', 'the')
# ('the', 'fourth')
# ('fourth', 'planet')
# ('planet', 'from')
# ('from', 'the')
# ('the', 'Sun')
# ('Sun', 'in')
# ('in', 'our')
# ('our', 'solar')
# ('solar', 'system,')
# ('system,', 'often')
# ('often', 'referred')
# ('referred', 'to')
# ('to', 'as')
# ('as', 'the')
# ('the', '“Red')
# ('“Red', 'Planet”')
# ('Planet”', 'due')
# ('due', 'to')
# ('to', 'its')
# ('its', 'reddish')
# ('reddish', 'appearance')
# ('appearance', 'caused')
# ('caused', 'by')
# ('by', 'iron')
# ('iron', 'oxide')
# ('oxide', 'on')
# ('on', 'its')
# ('its', 'surface.')
# ('surface.', 'Known')
# ('Known', 'for')
# ('for', 'its')
# ('its', 'towering')
# ('towering', 'volcanoes,')
# ('volcanoes,', 'vast')
# ('vast', 'deserts,')
# ('deserts,', 'and')
# ('and', 'polar')
# ('polar', 'ice')
# ('ice', 'caps,')
# ('caps,', 'Mars')
# ('Mars', 'has')
# ('has', 'long')
# ('long', 'fascinated')
# ('fascinated', 'scientists')
# ('scientists', 'as')
# ('as', 'a')
# ('a', 'potential')
# ('potential', 'candidate')
# ('candidate', 'for')
# ('for', 'future')
# ('future', 'human')
# ('human', 'exploration.')

# ***********   TRIGRAM    ************************
# ('Mars', 'is', 'the')
# ('is', 'the', 'fourth')
# ('the', 'fourth', 'planet')
# ('fourth', 'planet', 'from')
# ('planet', 'from', 'the')
# ('from', 'the', 'Sun')
# ('the', 'Sun', 'in')
# ('Sun', 'in', 'our')
# ('in', 'our', 'solar')
# ('our', 'solar', 'system,')
# ('solar', 'system,', 'often')
# ('system,', 'often', 'referred')
# ('often', 'referred', 'to')
# ('referred', 'to', 'as')
# ('to', 'as', 'the')
# ('as', 'the', '“Red')
# ('the', '“Red', 'Planet”')
# ('“Red', 'Planet”', 'due')
# ('Planet”', 'due', 'to')
# ('due', 'to', 'its')
# ('to', 'its', 'reddish')
# ('its', 'reddish', 'appearance')
# ('reddish', 'appearance', 'caused')
# ('appearance', 'caused', 'by')
# ('caused', 'by', 'iron')
# ('by', 'iron', 'oxide')
# ('iron', 'oxide', 'on')
# ('oxide', 'on', 'its')
# ('on', 'its', 'surface.')
# ('its', 'surface.', 'Known')
# ('surface.', 'Known', 'for')
# ('Known', 'for', 'its')
# ('for', 'its', 'towering')
# ('its', 'towering', 'volcanoes,')
# ('towering', 'volcanoes,', 'vast')
# ('volcanoes,', 'vast', 'deserts,')
# ('vast', 'deserts,', 'and')
# ('deserts,', 'and', 'polar')
# ('and', 'polar', 'ice')
# ('polar', 'ice', 'caps,')
# ('ice', 'caps,', 'Mars')
# ('caps,', 'Mars', 'has')
# ('Mars', 'has', 'long')
# ('has', 'long', 'fascinated')
# ('long', 'fascinated', 'scientists')
# ('fascinated', 'scientists', 'as')
# ('scientists', 'as', 'a')
# ('as', 'a', 'potential')
# ('a', 'potential', 'candidate')
# ('potential', 'candidate', 'for')
# ('candidate', 'for', 'future')
# ('for', 'future', 'human')
# ('future', 'human', 'exploration.')